# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'demo' do
  use_frameworks!

  pod 'AFNetworking'
  pod 'WZLBadge', '1.2.6'
  pod 'YYImage'
  #内部库
  pod 'DesignKit', :path => './Frameworks/DesignKit', :inhibit_warnings => false


end
